version: '3.8'

services:
  rpssl-service:
    build: .
    container_name: "rpssl-api"
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - random_number_base_url=https://codechallenge.boohma.com

