version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: "redis_server"
    ports:
     - "6379:6379"
    networks:
      - fullstack
  rpssl-service:
    build: .
    container_name: "rpssl-api"
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - random_number_base_url=https://codechallenge.boohma.com
      - REDIS_HOST=redis:6379
    depends_on:
      - redis
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge

